//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xo.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IXoGameService")]
    public interface IXoGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXoGameService/UpdateGame", ReplyAction="http://tempuri.org/IXoGameService/UpdateGameResponse")]
        int[] UpdateGame(int[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXoGameService/UpdateGame", ReplyAction="http://tempuri.org/IXoGameService/UpdateGameResponse")]
        System.Threading.Tasks.Task<int[]> UpdateGameAsync(int[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXoGameService/StartGame", ReplyAction="http://tempuri.org/IXoGameService/StartGameResponse")]
        void StartGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXoGameService/StartGame", ReplyAction="http://tempuri.org/IXoGameService/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXoGameServiceChannel : Xo.Client.ServiceReference1.IXoGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XoGameServiceClient : System.ServiceModel.ClientBase<Xo.Client.ServiceReference1.IXoGameService>, Xo.Client.ServiceReference1.IXoGameService {
        
        public XoGameServiceClient() {
        }
        
        public XoGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XoGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XoGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XoGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] UpdateGame(int[] data) {
            return base.Channel.UpdateGame(data);
        }
        
        public System.Threading.Tasks.Task<int[]> UpdateGameAsync(int[] data) {
            return base.Channel.UpdateGameAsync(data);
        }
        
        public void StartGame() {
            base.Channel.StartGame();
        }
        
        public System.Threading.Tasks.Task StartGameAsync() {
            return base.Channel.StartGameAsync();
        }
    }
}
